settings:
  title: 'Status Page'
  url: 'https://monitor.lwtech.tk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: github-page # unique identifier
    name: Github Page
    url: 'http://page.076111.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: dmhy
    name: 动漫花园
    # description: 'Built for anything connected to the Internet.' # default=empty
    url: 'https://www.dmhy.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: moegirl
    name: 萌娘百科
    url: 'https://zh.moegirl.org.cn/Mainpage'
    method: GET
    expectStatus: 200
    linkable: true
